"""Pure backtest-engine layer: baseline, zones, grids, paths, and crossings."""

from app.engine.crossing import (
    boundary_kind,
    determine_segment_direction,
    eligible_grid_levels,
    is_strictly_between,
    plan_grid_crossings,
    transition_rule,
)
from app.engine.grid import (
    MAX_GRID_LEVELS,
    EmptyDatasetError,
    GridCollapsesAfterTickRoundingError,
    GridTooDenseError,
    InvalidZoneConfigError,
    NonPositiveBaselineError,
    NonPositiveDistanceError,
    NonPositiveGridStepError,
    NonPositiveTickSizeError,
    build_grid_setup,
    build_zone_boundaries,
    canonical_grid_levels,
    classify_zone,
    generate_raw_grid_levels,
    resolve_absolute_value,
    resolve_baseline,
    resolve_grid_step,
    round_to_tick,
)
from app.engine.grid_models import GridSetup, TickSizeConfig, ValueConfig, ZoneBoundaries
from app.engine.path import (
    InvalidOhlcvBarError,
    OhlcPathModeRequiredError,
    build_close_only_path,
    build_ohlcv_path,
    build_path_segments,
    build_price_path,
    initialize_path_state,
    select_ohlc_midpoints,
)
from app.engine.path_models import InitialPathState, PathSegment
from app.engine.segment import (
    InvalidZoneTransitionError,
    apply_boundary_transition,
    create_traversal_state,
    plan_segment_actions,
)
from app.engine.segment_models import (
    BoundaryKind,
    PlannedGridCrossing,
    SegmentDirection,
    SegmentTraversalState,
    TransitionRule,
    ZoneEvent,
)

__all__ = [
    "BoundaryKind",
    "EmptyDatasetError",
    "GridCollapsesAfterTickRoundingError",
    "GridSetup",
    "GridTooDenseError",
    "InitialPathState",
    "InvalidOhlcvBarError",
    "InvalidZoneConfigError",
    "InvalidZoneTransitionError",
    "MAX_GRID_LEVELS",
    "NonPositiveBaselineError",
    "NonPositiveDistanceError",
    "NonPositiveGridStepError",
    "NonPositiveTickSizeError",
    "OhlcPathModeRequiredError",
    "PathSegment",
    "PlannedGridCrossing",
    "SegmentDirection",
    "SegmentTraversalState",
    "TickSizeConfig",
    "TransitionRule",
    "ValueConfig",
    "ZoneBoundaries",
    "ZoneEvent",
    "apply_boundary_transition",
    "boundary_kind",
    "build_close_only_path",
    "build_grid_setup",
    "build_ohlcv_path",
    "build_path_segments",
    "build_price_path",
    "build_zone_boundaries",
    "canonical_grid_levels",
    "classify_zone",
    "create_traversal_state",
    "determine_segment_direction",
    "eligible_grid_levels",
    "generate_raw_grid_levels",
    "initialize_path_state",
    "is_strictly_between",
    "plan_grid_crossings",
    "plan_segment_actions",
    "resolve_absolute_value",
    "resolve_baseline",
    "resolve_grid_step",
    "round_to_tick",
    "select_ohlc_midpoints",
    "transition_rule",
]
