"""In-memory PDF backtest report (SPEC Sections 25.4, 32).

The report is assembled entirely from persisted rows -- BacktestRun, its
Dataset, the stored configuration/result_metrics documents, and the
normalized DailyEquity/Trade series. The engine is never invoked, no metric
is recomputed, and no bytes are written to disk: the document is built into
a BytesIO and returned.

Section order is frozen by SPEC 32 and followed exactly:

  1 name, 2 security, 3 data range, 4 cleaning summary, 5 strategy
  parameters, 6 fee/slippage, 7 OHLC-path assumption, 8 core metrics,
  9 both benchmarks, 10 price chart, 11 equity curve, 12 drawdown chart,
  13 first 20 trades, 14 cost summary, 15 risk disclaimer.

Decimal values are carried as Decimal/str end to end; a float appears only
at the final graphics-coordinate boundary inside the chart helpers, never in
rendered metric text.
"""

import datetime
import io
from decimal import Decimal, InvalidOperation
from typing import Any, Final

from reportlab.graphics.shapes import Drawing, Line, PolyLine, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy.orm import Session

from app.backtests.projections import load_daily_equity_projection, load_trade_projection
from app.db.models import BacktestRun

__all__ = ["FIRST_TRADE_ROWS", "RISK_DISCLAIMER", "build_backtest_pdf_report"]

# SPEC 32 item 13: the report carries the first 20 trades only; the complete
# history stays available through trades.csv.
FIRST_TRADE_ROWS: Final[int] = 20

RISK_DISCLAIMER: Final[str] = (
    "This report is generated by a research and educational backtesting tool. "
    "It does not constitute investment advice. Past performance, whether real "
    "or simulated, does not guarantee future results."
)

# Built into ReportLab: a standard CJK CID font that needs no tracked font
# file. Latin text keeps Helvetica so ordinary numerics stay consistent.
_CJK_FONT: Final[str] = "STSong-Light"
_LATIN_FONT: Final[str] = "Helvetica"
_LATIN_BOLD: Final[str] = "Helvetica-Bold"

_PAGE_SIZE = A4
_MARGIN = 18 * mm
_CONTENT_WIDTH = _PAGE_SIZE[0] - 2 * _MARGIN

_STRATEGY_COLOR = colors.HexColor("#1f4e79")
_BENCHMARK1_COLOR = colors.HexColor("#c00000")
_BENCHMARK2_COLOR = colors.HexColor("#2e7d32")
_GRID_COLOR = colors.HexColor("#d9d9d9")
_AXIS_COLOR = colors.HexColor("#666666")

_cjk_registered = False


def _ensure_fonts() -> None:
    """Register the CJK CID font once per process."""
    global _cjk_registered
    if not _cjk_registered:
        pdfmetrics.registerFont(UnicodeCIDFont(_CJK_FONT))
        _cjk_registered = True


def _needs_cjk(text: str) -> bool:
    return any(ord(char) > 0x2FF for char in text)


# --------------------------------------------------------------------------
# value rendering -- stored strings stay strings; no float is ever involved
# --------------------------------------------------------------------------


def _dash(value: object) -> str:
    """Render a missing value consistently."""
    return "-" if value is None else str(value)


def _yes_no(value: object) -> str:
    if value is None:
        return "-"
    return "Yes" if bool(value) else "No"


def _enabled(value: object) -> str:
    if value is None:
        return "-"
    return "Enabled" if bool(value) else "Disabled"


def _decimal(value: object) -> Decimal | None:
    """Parse a stored decimal string without ever going through float."""
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, Decimal):
        return value
    if isinstance(value, int):
        return Decimal(value)
    if isinstance(value, str):
        try:
            return Decimal(value)
        except InvalidOperation:
            return None
    return None


def _quantize(value: object, places: int = 6) -> str:
    """Fixed-point rendering of a ratio-style metric; never scientific."""
    parsed = _decimal(value)
    if parsed is None:
        return "-"
    exponent = Decimal(1).scaleb(-places)
    return format(parsed.quantize(exponent), "f")


def _percent(value: object, places: int = 4) -> str:
    """Human-readable percentage label alongside the stored ratio."""
    parsed = _decimal(value)
    if parsed is None:
        return "-"
    exponent = Decimal(1).scaleb(-places)
    return f"{format((parsed * 100).quantize(exponent), 'f')}%"


def _ratio(value: object) -> str:
    if _decimal(value) is None:
        return "-"
    return f"{_quantize(value)}  ({_percent(value)})"


def _money(value: object) -> str:
    """Monetary/price values render exactly as stored (already fixed-point)."""
    parsed = _decimal(value)
    if parsed is None:
        return "-"
    return format(parsed, "f")


def _int_text(value: object) -> str:
    if value is None:
        return "-"
    if isinstance(value, bool):
        return _yes_no(value)
    if isinstance(value, int):
        return str(value)
    return str(value)


def _date_text(value: datetime.date | None) -> str:
    return "-" if value is None else value.isoformat()


def _timestamp_text(value: datetime.datetime | None) -> str:
    if value is None:
        return "-"
    return value.replace(microsecond=0).isoformat()


def _value_config(config: object, *, unit: str = "") -> str:
    """Render a {mode, value} distance/step block readably."""
    if not isinstance(config, dict):
        return _dash(config)
    mode = config.get("mode")
    raw = config.get("value")
    if raw is None:
        return "-"
    if mode == "PERCENT":
        return f"{_money(raw)} ({_percent(raw)}, percent mode)"
    return f"{_money(raw)}{unit} (fixed mode)"


def _commission_text(config: object) -> str:
    if not isinstance(config, dict):
        return _dash(config)
    parts = [
        f"rate {_enabled(config.get('rate_enabled'))} @ {_money(config.get('rate'))}",
        f"minimum {_enabled(config.get('minimum_enabled'))} @ {_money(config.get('minimum'))}",
        f"fixed {_enabled(config.get('fixed_enabled'))} @ {_money(config.get('fixed'))}",
    ]
    return "; ".join(parts)


def _slippage_text(config: object) -> str:
    if not isinstance(config, dict):
        return _dash(config)
    mode = _dash(config.get("mode"))
    if config.get("shared"):
        return f"Shared, {mode} @ {_money(config.get('value'))}"
    return f"Separate, {mode} - buy {_money(config.get('buy'))}, sell {_money(config.get('sell'))}"


# --------------------------------------------------------------------------
# styles and flowable helpers
# --------------------------------------------------------------------------


class _Styles:
    """Paragraph styles; CJK-capable variants pick the CID font."""

    def __init__(self) -> None:
        sample = getSampleStyleSheet()
        self.title = ParagraphStyle(
            "ReportTitle",
            parent=sample["Title"],
            fontName=_LATIN_BOLD,
            fontSize=18,
            leading=22,
            spaceAfter=2,
        )
        self.title_cjk = ParagraphStyle("ReportTitleCJK", parent=self.title, fontName=_CJK_FONT)
        self.subtitle = ParagraphStyle(
            "ReportSubtitle",
            parent=sample["Normal"],
            fontName=_LATIN_FONT,
            fontSize=9.5,
            leading=12,
            textColor=colors.HexColor("#555555"),
            alignment=TA_CENTER,
            spaceAfter=8,
        )
        self.heading = ParagraphStyle(
            "SectionHeading",
            parent=sample["Heading2"],
            fontName=_LATIN_BOLD,
            fontSize=12,
            leading=15,
            spaceBefore=10,
            spaceAfter=5,
            textColor=_STRATEGY_COLOR,
            # A heading never sits alone at the foot of a page.
            keepWithNext=True,
        )
        self.body = ParagraphStyle(
            "Body", parent=sample["Normal"], fontName=_LATIN_FONT, fontSize=8.5, leading=11
        )
        self.body_cjk = ParagraphStyle("BodyCJK", parent=self.body, fontName=_CJK_FONT)
        self.cell = ParagraphStyle(
            "Cell", parent=sample["Normal"], fontName=_LATIN_FONT, fontSize=8, leading=10
        )
        self.cell_cjk = ParagraphStyle("CellCJK", parent=self.cell, fontName=_CJK_FONT)
        self.cell_head = ParagraphStyle(
            "CellHead",
            parent=self.cell,
            fontName=_LATIN_BOLD,
            fontSize=6.5,
            leading=8,
            textColor=colors.white,
        )
        # Denser style for the wide trade grid, so numeric columns fit on one line.
        self.compact = ParagraphStyle(
            "Compact", parent=self.cell, fontName=_LATIN_FONT, fontSize=6.5, leading=8
        )
        self.compact_cjk = ParagraphStyle("CompactCJK", parent=self.compact, fontName=_CJK_FONT)
        self.note = ParagraphStyle(
            "Note",
            parent=self.body,
            fontSize=8,
            textColor=colors.HexColor("#8a6d3b"),
            spaceBefore=2,
        )
        self.disclaimer = ParagraphStyle(
            "Disclaimer",
            parent=self.body,
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#444444"),
        )

    def para(self, text: str, latin: ParagraphStyle, cjk: ParagraphStyle) -> Paragraph:
        escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return Paragraph(escaped, cjk if _needs_cjk(text) else latin)

    def cell_para(self, text: str) -> Paragraph:
        return self.para(text, self.cell, self.cell_cjk)

    def body_para(self, text: str) -> Paragraph:
        return self.para(text, self.body, self.body_cjk)

    def compact_para(self, text: str) -> Paragraph:
        return self.para(text, self.compact, self.compact_cjk)


def _key_value_table(styles: _Styles, rows: list[tuple[str, str]]) -> Table:
    """Two-column label/value table that wraps and repeats no header."""
    data = [[styles.cell_para(label), styles.cell_para(value)] for label, value in rows]
    table = Table(data, colWidths=[_CONTENT_WIDTH * 0.34, _CONTENT_WIDTH * 0.66], repeatRows=0)
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f5f9")),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    return table


def _grid_table(
    styles: _Styles,
    header: list[str],
    rows: list[list[str]],
    *,
    weights: list[float] | None = None,
) -> Table:
    """Multi-column table whose header row repeats across page breaks.

    ``weights`` gives each column a share of the content width so numeric
    columns stay wide enough to hold a value on one line.
    """
    column_count = len(header)
    shares = weights or [1.0] * column_count
    total = sum(shares)
    widths = [_CONTENT_WIDTH * share / total for share in shares]
    data: list[list[Paragraph]] = [
        [Paragraph(name, styles.cell_head) for name in header],
        *[[styles.compact_para(cell) for cell in row] for row in rows],
    ]
    table = Table(data, colWidths=widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("BACKGROUND", (0, 0), (-1, 0), _STRATEGY_COLOR),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f9fb")]),
            ]
        )
    )
    return table


# --------------------------------------------------------------------------
# charts -- Decimal becomes float only here, at the coordinate boundary
# --------------------------------------------------------------------------

_CHART_WIDTH = _CONTENT_WIDTH
_CHART_HEIGHT = 175.0
_PLOT_LEFT = 62.0
_PLOT_BOTTOM = 26.0
_PLOT_TOP = 18.0
_PLOT_RIGHT = 8.0


def _chart_bounds() -> tuple[float, float, float, float]:
    left = _PLOT_LEFT
    bottom = _PLOT_BOTTOM
    width = _CHART_WIDTH - _PLOT_LEFT - _PLOT_RIGHT
    height = _CHART_HEIGHT - _PLOT_BOTTOM - _PLOT_TOP
    return left, bottom, width, height


def _line_chart(
    *,
    title: str,
    labels: list[str],
    series: list[tuple[str, list[Decimal], colors.Color, tuple[int, int] | None]],
    reference_lines: list[tuple[str, Decimal, colors.Color]] | None = None,
    faint_lines: list[Decimal] | None = None,
) -> Drawing:
    """A self-contained line chart drawn from ReportLab primitives.

    Handles empty and single-point series safely and keeps every mark inside
    the drawing's bounds, so nothing can spill outside the page frame.
    """
    drawing = Drawing(_CHART_WIDTH, _CHART_HEIGHT)
    left, bottom, width, height = _chart_bounds()

    drawing.add(
        String(
            0, _CHART_HEIGHT - 11, title, fontName=_LATIN_BOLD, fontSize=9.5, fillColor=colors.black
        )
    )

    plotted = [(label, values, color, dashes) for label, values, color, dashes in series if values]
    if not plotted:
        drawing.add(
            String(
                left,
                bottom + height / 2,
                "No series data available.",
                fontName=_LATIN_FONT,
                fontSize=8.5,
                fillColor=_AXIS_COLOR,
            )
        )
        return drawing

    candidates: list[Decimal] = [value for _, values, _, _ in plotted for value in values]
    for _, reference, _ in reference_lines or []:
        candidates.append(reference)
    for reference in faint_lines or []:
        candidates.append(reference)

    low = min(candidates)
    high = max(candidates)
    if low == high:  # flat or single-point series
        pad = abs(low) / 10 if low != 0 else Decimal("1")
        low, high = low - pad, high + pad
    span = high - low

    point_count = max(len(values) for _, values, _, _ in plotted)

    def to_y(value: Decimal) -> float:
        # Decimal -> float only here, purely to obtain a canvas coordinate.
        ratio = (value - low) / span
        return bottom + float(ratio) * height

    def to_x(index: int) -> float:
        if point_count <= 1:
            return left + width / 2
        return left + (index / (point_count - 1)) * width

    # plot frame and horizontal guides
    drawing.add(
        Rect(left, bottom, width, height, strokeColor=_AXIS_COLOR, strokeWidth=0.5, fillColor=None)
    )
    for step in range(1, 4):
        y = bottom + height * step / 4
        drawing.add(Line(left, y, left + width, y, strokeColor=_GRID_COLOR, strokeWidth=0.3))

    # y-axis labels
    for step in range(5):
        value = low + span * Decimal(step) / Decimal(4)
        y = bottom + height * step / 4
        drawing.add(
            String(
                left - 5,
                y - 3,
                format(value.quantize(Decimal("0.0001")), "f"),
                fontName=_LATIN_FONT,
                fontSize=6,
                fillColor=_AXIS_COLOR,
                textAnchor="end",
            )
        )

    # faint reference levels (grid levels) behind the data
    for reference in faint_lines or []:
        y = to_y(reference)
        drawing.add(Line(left, y, left + width, y, strokeColor=_GRID_COLOR, strokeWidth=0.3))

    # named reference levels (baseline / A / C boundaries)
    for label, reference, color in reference_lines or []:
        y = to_y(reference)
        line = Line(left, y, left + width, y, strokeColor=color, strokeWidth=0.6)
        line.strokeDashArray = [3, 2]
        drawing.add(line)
        drawing.add(
            String(
                left + width - 2,
                y + 2,
                label,
                fontName=_LATIN_FONT,
                fontSize=5.5,
                fillColor=color,
                textAnchor="end",
            )
        )

    # data series
    for _, values, color, dashes in plotted:
        if len(values) == 1:
            y = to_y(values[0])
            drawing.add(Line(left, y, left + width, y, strokeColor=color, strokeWidth=1.1))
            continue
        coordinates: list[float] = []
        for index, value in enumerate(values):
            coordinates.extend([to_x(index), to_y(value)])
        poly = PolyLine(coordinates, strokeColor=color, strokeWidth=0.9)
        if dashes is not None:
            poly.strokeDashArray = list(dashes)
        drawing.add(poly)

    # x-axis labels: a handful of evenly spaced dates
    if labels:
        ticks = min(6, len(labels))
        for step in range(ticks):
            index = 0 if ticks == 1 else round(step * (len(labels) - 1) / (ticks - 1))
            drawing.add(
                String(
                    to_x(index),
                    bottom - 10,
                    labels[index],
                    fontName=_LATIN_FONT,
                    fontSize=6,
                    fillColor=_AXIS_COLOR,
                    textAnchor="middle",
                )
            )

    # legend along the bottom
    legend_x = left
    for label, _, color, _ in plotted:
        drawing.add(Line(legend_x, 6, legend_x + 12, 6, strokeColor=color, strokeWidth=1.2))
        drawing.add(
            String(
                legend_x + 15,
                3.5,
                label,
                fontName=_LATIN_FONT,
                fontSize=6.5,
                fillColor=colors.black,
            )
        )
        legend_x += 22 + len(label) * 3.6

    return drawing


def _zero_reference_chart(*, title: str, labels: list[str], values: list[Decimal]) -> Drawing:
    """Drawdown chart: negative values preserved, zero line included."""
    return _line_chart(
        title=title,
        labels=labels,
        series=[("Drawdown", values, _BENCHMARK1_COLOR, None)],
        reference_lines=[("0", Decimal(0), _AXIS_COLOR)] if values else None,
    )


# --------------------------------------------------------------------------
# stored-document accessors
# --------------------------------------------------------------------------


def _mapping(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _benchmark_points(metrics: dict[str, Any], key: str) -> list[Decimal]:
    points = _mapping(metrics.get(key)).get("points")
    if not isinstance(points, list):
        return []
    values: list[Decimal] = []
    for point in points:
        parsed = _decimal(_mapping(point).get("equity"))
        if parsed is not None:
            values.append(parsed)
    return values


def _equity_series_rows(label: str, series: dict[str, Any]) -> list[tuple[str, str]]:
    return [
        (f"{label} - Initial Equity", _money(series.get("initial_equity"))),
        (f"{label} - Final Equity", _money(series.get("final_equity"))),
        (f"{label} - Net Profit", _money(series.get("net_profit"))),
        (f"{label} - Total Return", _ratio(series.get("total_return"))),
        (f"{label} - Annualized Return", _ratio(series.get("annualized_return"))),
        (f"{label} - Maximum Drawdown", _ratio(series.get("maximum_drawdown"))),
        (f"{label} - Sharpe Ratio", _quantize(series.get("sharpe_ratio"))),
    ]


# --------------------------------------------------------------------------
# page furniture
# --------------------------------------------------------------------------


def _page_decoration(canvas: Any, document: Any) -> None:
    """Footer with the page number on every page."""
    canvas.saveState()
    canvas.setFont(_LATIN_FONT, 7.5)
    canvas.setFillColor(colors.HexColor("#777777"))
    canvas.drawCentredString(_PAGE_SIZE[0] / 2, _MARGIN * 0.55, f"Page {canvas.getPageNumber()}")
    canvas.drawRightString(_PAGE_SIZE[0] - _MARGIN, _MARGIN * 0.55, "Grid Backtester")
    canvas.restoreState()


# --------------------------------------------------------------------------
# the builder
# --------------------------------------------------------------------------


def build_backtest_pdf_report(session: Session, *, run: BacktestRun) -> bytes:
    """Render one owned BacktestRun to PDF bytes.

    Ownership must already be resolved by the caller. Read-only: the two
    series queries are ordered projections and nothing is written, flushed,
    or committed.
    """
    _ensure_fonts()
    styles = _Styles()

    dataset = run.dataset
    configuration = _mapping(run.configuration)
    metrics_document = _mapping(run.result_metrics)
    has_result = run.result_metrics is not None
    inner = _mapping(metrics_document.get("metrics"))
    strategy = _mapping(inner.get("strategy"))
    trade_costs = _mapping(inner.get("trade_costs"))
    zones = _mapping(inner.get("zones"))
    first_return = _mapping(inner.get("first_return"))

    daily_rows = load_daily_equity_projection(session, backtest_run_id=run.id)
    trades = load_trade_projection(session, backtest_run_id=run.id, limit=FIRST_TRADE_ROWS)

    story: list[Any] = []

    # 1. Project/backtest name -------------------------------------------------
    story.append(styles.para(run.name, styles.title, styles.title_cjk))
    story.append(
        Paragraph(
            f"Backtest #{run.id} &middot; Status {run.status} &middot; "
            f"Created {_timestamp_text(run.created_at)} &middot; "
            f"Completed {_timestamp_text(run.completed_at)}",
            styles.subtitle,
        )
    )

    # 2/3/4. Security information, data range, cleaning summary ---------------
    story.append(Paragraph("Security and Dataset", styles.heading))
    story.append(
        _key_value_table(
            styles,
            [
                ("Security Name", _dash(dataset.security_name)),
                ("Security Code", _dash(dataset.security_code)),
                ("Dataset Name", dataset.name),
                ("Source Type", dataset.source_type),
                ("Original Filename", dataset.original_filename),
                ("Data Mode", dataset.data_mode),
                (
                    "Dataset Range",
                    f"{_date_text(dataset.start_date)} to {_date_text(dataset.end_date)}",
                ),
                ("Backtest Range", f"{_date_text(run.start_date)} to {_date_text(run.end_date)}"),
                ("Row Count", _int_text(dataset.row_count)),
            ],
        )
    )

    story.append(Paragraph("Data-Cleaning Summary", styles.heading))
    cleaning = _mapping(dataset.cleaning_summary)
    if cleaning:
        story.append(
            _key_value_table(
                styles,
                [
                    (str(key), _dash(value) if not isinstance(value, dict | list) else str(value))
                    for key, value in cleaning.items()
                ],
            )
        )
    else:
        story.append(styles.body_para("No cleaning summary recorded for this dataset."))

    # 5. Strategy parameters ---------------------------------------------------
    story.append(Paragraph("Strategy Parameters", styles.heading))
    story.append(
        _key_value_table(
            styles,
            [
                ("Initial Cash", _money(configuration.get("initial_cash"))),
                ("Initial Shares", _int_text(configuration.get("initial_shares"))),
                ("Lot Size", _int_text(configuration.get("lot_size"))),
                ("Trade Lots", _int_text(configuration.get("trade_lots"))),
                (
                    "Baseline",
                    _money(configuration.get("baseline"))
                    if configuration.get("baseline") is not None
                    else "- (default: first Close)",
                ),
                ("A Distance", _value_config(configuration.get("a_distance"))),
                ("C Distance", _value_config(configuration.get("c_distance"))),
                ("Grid Step", _value_config(configuration.get("grid_step"))),
                (
                    "Tick Size",
                    f"{_enabled(_mapping(configuration.get('tick_size')).get('enabled'))}"
                    f" @ {_money(_mapping(configuration.get('tick_size')).get('value'))}",
                ),
                ("Risk-Free Rate (annual)", _ratio(configuration.get("risk_free_rate_annual"))),
            ],
        )
    )

    if has_result:
        story.append(Paragraph("Baseline and Grid Geometry", styles.heading))
        grid_levels = metrics_document.get("grid_levels")
        level_count = len(grid_levels) if isinstance(grid_levels, list) else 0
        story.append(
            _key_value_table(
                styles,
                [
                    ("Baseline", _money(metrics_document.get("baseline"))),
                    ("A Zone Lower", _money(metrics_document.get("a_lower"))),
                    ("A Zone Upper", _money(metrics_document.get("a_upper"))),
                    ("C Zone Lower", _money(metrics_document.get("c_lower"))),
                    ("C Zone Upper", _money(metrics_document.get("c_upper"))),
                    ("Grid Step Size", _money(metrics_document.get("grid_step"))),
                    ("Grid Level Count", _int_text(level_count)),
                ],
            )
        )

    # 6. Fee and slippage assumptions -----------------------------------------
    story.append(Paragraph("Fee and Slippage Assumptions", styles.heading))
    story.append(
        _key_value_table(
            styles,
            [
                ("Buy Commission", _commission_text(configuration.get("buy_commission"))),
                ("Sell Commission", _commission_text(configuration.get("sell_commission"))),
                ("Slippage", _slippage_text(configuration.get("slippage"))),
            ],
        )
    )

    # 7. OHLC-path assumption --------------------------------------------------
    story.append(Paragraph("OHLC-Path Assumption", styles.heading))
    if dataset.data_mode == "CLOSE_ONLY":
        story.append(
            styles.body_para(
                "Data mode is CLOSE_ONLY: the dataset carries no intraday high/low, "
                "so no OHLC path was reconstructed and the configured path mode "
                f"({_dash(configuration.get('ohlc_path_mode'))}) was not applied."
            )
        )
    else:
        story.append(
            _key_value_table(
                styles,
                [
                    ("Configured Path Mode", _dash(configuration.get("ohlc_path_mode"))),
                    ("Stored Path Mode", _dash(run.ohlc_path_mode)),
                ],
            )
        )

    # 8. Core metrics ----------------------------------------------------------
    story.append(Paragraph("Core Metrics", styles.heading))
    if has_result:
        final_state = _mapping(metrics_document.get("final_state"))
        story.append(
            _key_value_table(
                styles,
                [
                    ("Initial Equity", _money(strategy.get("initial_equity"))),
                    ("Final Equity", _money(strategy.get("final_equity"))),
                    ("Net Profit", _money(strategy.get("net_profit"))),
                    ("Total Return", _ratio(strategy.get("total_return"))),
                    ("Annualized Return", _ratio(strategy.get("annualized_return"))),
                    ("Maximum Drawdown", _ratio(strategy.get("maximum_drawdown"))),
                    ("Sharpe Ratio", _quantize(strategy.get("sharpe_ratio"))),
                    ("First Return Equity", _money(first_return.get("equity"))),
                    ("Days Until First Return", _int_text(first_return.get("days"))),
                    ("Final Cash", _money(final_state.get("cash"))),
                    ("Final Shares", _int_text(final_state.get("shares"))),
                    ("Final Zone State", _dash(final_state.get("zone_state"))),
                ],
            )
        )

        story.append(Paragraph("Trade and Zone Statistics", styles.heading))
        zone_counts = _mapping(zones.get("zone_event_counts"))
        story.append(
            _key_value_table(
                styles,
                [
                    ("Executed Trades", _int_text(trade_costs.get("executed_trades"))),
                    ("Skipped Trades", _int_text(trade_costs.get("skipped_trades"))),
                    ("BUY Count", _int_text(trade_costs.get("buy_count"))),
                    ("SELL Count", _int_text(trade_costs.get("sell_count"))),
                    ("Days Closed in A Zone", _int_text(zones.get("days_closed_in_a_zone"))),
                    ("Days Closed in C Zone", _int_text(zones.get("days_closed_in_c_zone"))),
                    ("Days Closed Outside C", _int_text(zones.get("days_closed_outside_c"))),
                    *[
                        (f"Zone Event: {name}", _int_text(count))
                        for name, count in zone_counts.items()
                    ],
                ],
            )
        )
    else:
        story.append(
            styles.body_para("Result data is unavailable for this run, so no metrics are shown.")
        )

    # 9. Both Buy-and-Hold benchmarks -----------------------------------------
    story.append(Paragraph("Buy-and-Hold Benchmarks", styles.heading))
    if has_result:
        benchmark_rows = [
            *_equity_series_rows("Benchmark 1", _mapping(inner.get("benchmark1"))),
            *_equity_series_rows("Benchmark 2", _mapping(inner.get("benchmark2"))),
        ]
        story.append(_key_value_table(styles, benchmark_rows))

        day_one = _mapping(_mapping(metrics_document.get("benchmark2")).get("day_one_purchase"))
        story.append(Paragraph("Benchmark 2 Day-One Purchase", styles.heading))
        if day_one:
            story.append(
                _key_value_table(
                    styles,
                    [
                        ("Reference Price", _money(day_one.get("reference_price"))),
                        ("Tick Price", _money(day_one.get("tick_price"))),
                        ("Execution Price", _money(day_one.get("execution_price"))),
                        ("Lots", _int_text(day_one.get("lots"))),
                        ("Shares Purchased", _int_text(day_one.get("shares_purchased"))),
                        ("Notional", _money(day_one.get("notional"))),
                        ("Commission", _money(day_one.get("commission"))),
                        ("Slippage Cost", _money(day_one.get("slippage_cost"))),
                        ("Cash After", _money(day_one.get("cash_after"))),
                        ("Shares After", _int_text(day_one.get("shares_after"))),
                    ],
                )
            )
        else:
            story.append(styles.body_para("No day-one purchase was recorded."))
    else:
        story.append(styles.body_para("Benchmark data is unavailable for this run."))

    # 10/11/12. Charts ---------------------------------------------------------
    labels = [row.date.isoformat() for row in daily_rows]

    story.append(Paragraph("Price and Grid Geometry", styles.heading))
    if daily_rows:
        reference_lines: list[tuple[str, Decimal, colors.Color]] = []
        faint: list[Decimal] = []
        if has_result:
            for label, key, color in (
                ("Baseline", "baseline", _STRATEGY_COLOR),
                ("A Lower", "a_lower", _BENCHMARK2_COLOR),
                ("A Upper", "a_upper", _BENCHMARK2_COLOR),
                ("C Lower", "c_lower", _BENCHMARK1_COLOR),
                ("C Upper", "c_upper", _BENCHMARK1_COLOR),
            ):
                parsed = _decimal(metrics_document.get(key))
                if parsed is not None:
                    reference_lines.append((label, parsed, color))
            levels = metrics_document.get("grid_levels")
            if isinstance(levels, list):
                faint = [
                    parsed for parsed in (_decimal(level) for level in levels) if parsed is not None
                ]
        story.append(
            _line_chart(
                title="Daily Close with Baseline, A/C Boundaries and Grid Levels",
                labels=labels,
                series=[("Close", [row.close for row in daily_rows], _STRATEGY_COLOR, None)],
                reference_lines=reference_lines,
                faint_lines=faint,
            )
        )
    else:
        story.append(styles.body_para("No daily price series is available for this run."))

    story.append(Spacer(1, 10))
    story.append(Paragraph("Equity Curve", styles.heading))
    if daily_rows:
        story.append(
            _line_chart(
                title="Daily Close Equity vs Buy-and-Hold Benchmarks",
                labels=labels,
                series=[
                    ("Strategy", [row.equity for row in daily_rows], _STRATEGY_COLOR, None),
                    (
                        "Benchmark 1",
                        _benchmark_points(metrics_document, "benchmark1"),
                        _BENCHMARK1_COLOR,
                        (4, 2),
                    ),
                    (
                        "Benchmark 2",
                        _benchmark_points(metrics_document, "benchmark2"),
                        _BENCHMARK2_COLOR,
                        (1, 2),
                    ),
                ],
            )
        )
    else:
        story.append(styles.body_para("No equity series is available for this run."))

    story.append(Spacer(1, 10))
    story.append(Paragraph("Drawdown", styles.heading))
    if daily_rows:
        story.append(
            _zero_reference_chart(
                title="Daily Drawdown",
                labels=labels,
                values=[row.drawdown for row in daily_rows],
            )
        )
    else:
        story.append(styles.body_para("No drawdown series is available for this run."))

    # 13. First 20 trades ------------------------------------------------------
    story.append(Paragraph(f"First {FIRST_TRADE_ROWS} Trades", styles.heading))
    if trades:
        rows = [
            [
                str(sequence),
                event_date.isoformat(),
                trade.side,
                _money(trade.grid_price),
                _money(trade.execution_price),
                _int_text(trade.shares),
                _money(trade.notional),
                _money(trade.commission),
                _money(trade.equity_after),
                trade.status,
                _dash(trade.skip_reason),
            ]
            for trade, event_date, sequence in trades
        ]
        story.append(
            _grid_table(
                styles,
                [
                    "Seq",
                    "Date",
                    "Side",
                    "Grid",
                    "Exec",
                    "Shares",
                    "Notional",
                    "Comm",
                    "Equity",
                    "Status",
                    "Skip",
                ],
                rows,
                # Skip reasons are long unbroken tokens, so that column gets
                # the widest share after Equity.
                weights=[3.5, 8.5, 4.5, 8.0, 8.0, 6.0, 8.5, 7.5, 11.0, 8.0, 12.0],
            )
        )
        story.append(
            Paragraph(
                f"Showing the first {len(rows)} trade(s) ordered by event sequence. "
                "The complete trade history is available from trades.csv.",
                styles.note,
            )
        )
    else:
        story.append(styles.body_para("This run recorded no trades."))

    # 14. Cost summary ---------------------------------------------------------
    story.append(Paragraph("Cost Summary", styles.heading))
    if has_result:
        story.append(
            _key_value_table(
                styles,
                [
                    ("Total Commission", _money(trade_costs.get("total_commission"))),
                    ("Total Slippage Cost", _money(trade_costs.get("total_slippage_cost"))),
                    (
                        "Benchmark 2 Day-One Commission",
                        _money(inner.get("benchmark2_day_one_commission")),
                    ),
                    (
                        "Benchmark 2 Day-One Slippage Cost",
                        _money(inner.get("benchmark2_day_one_slippage_cost")),
                    ),
                ],
            )
        )
    else:
        story.append(styles.body_para("Cost data is unavailable for this run."))

    # Failure section ----------------------------------------------------------
    if run.status != "COMPLETED":
        story.append(Paragraph(f"Run Status: {run.status}", styles.heading))
        story.append(
            _key_value_table(
                styles,
                [
                    ("Status", run.status),
                    ("Error Message", _dash(run.error_message)),
                    (
                        "Result Data",
                        "Unavailable - this run produced no stored result document."
                        if not has_result
                        else "Partial result data is stored for this run.",
                    ),
                ],
            )
        )
        story.append(
            Paragraph(
                "No metrics, benchmarks, or charts are synthesized for a run that did "
                "not complete successfully.",
                styles.note,
            )
        )

    # 15. Risk disclaimer ------------------------------------------------------
    story.append(Spacer(1, 12))
    story.append(
        KeepTogether(
            [
                Paragraph("Risk Disclaimer", styles.heading),
                Paragraph(RISK_DISCLAIMER, styles.disclaimer),
            ]
        )
    )

    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=_PAGE_SIZE,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=_MARGIN,
        # Safe metadata only: never the editable run name, an email, a path,
        # or anything credential-bearing.
        title=f"Backtest Report {run.id}",
        author="Grid Backtester",
        subject="Backtest result report",
        creator="Grid Backtester",
    )
    document.build(story, onFirstPage=_page_decoration, onLaterPages=_page_decoration)
    return buffer.getvalue()
